name: Go Build & Format
on:
  push:
    branches-ignore:
      - "master"
    tags-ignore:
      - "*"
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: setup go
        uses: actions/setup-go@v4
        with:
          go-version-file: ./app/go.mod
          cache: true
          cache-dependency-path: ./app/go.sum
      - uses: dominikh/staticcheck-action@v1.3.0
        with:
          version: "2023.1.2"
          install-go: false
      - run: go version
      - uses: actions/checkout@v3
      - run: go fmt .
      - run: go build -v .
